spring.application.name=employee
server.port=3434
spring.datasource.url=jdbc:postgresql://localhost:8080/employee_system
spring.datasource.username=postgres
spring.datasource.password=0000
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
